'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const gate=fs.readFileSync('shared/atlas-account-gate.js','utf8');
const compass=fs.readFileSync('compass/index.html','utf8');
assert.ok(gate.includes("'atlas:account-confirmed-elsewhere'"));
assert.ok(gate.includes("'atlas:account-confirmation-acknowledged'"));
assert.ok(gate.includes('confirmationPendingIntentId'));
assert.ok(gate.includes('confirmationPendingIntent'));
assert.ok(gate.includes('returnIntent\n                    );'));
assert.ok(gate.includes('Confirm your email address to activate your Atlas account.'));
assert.ok(gate.includes('accountCopy.hidden = true'));
assert.ok(gate.includes("messageClose.textContent = 'Got it'"));
assert.ok(compass.includes("'atlas::returnIntentResume::v1'"));
assert.ok(compass.includes('atlasResumeTransition'));
assert.ok(compass.includes("content: 'Building your subject…'"));
assert.ok(compass.includes("'account-confirmation'"));
assert.ok(compass.includes('silentResume'));
assert.ok(compass.includes("'atlas:account-confirmation-acknowledged'"));
assert.ok(compass.includes("'atlas:account-confirmed-elsewhere'"));
assert.ok(compass.includes('closePendingCreateSubjectUI'));
assert.ok(compass.includes("trigger,\n          'create'"));
console.log('Atlas 5.1 signup continuation UX contract passed.');
