// Authored seed bank. Opening rungs recalibrated 2026-10-04; remaining bank reviewed 2026-10-02.
// Evidence is paraphrased; mathematical questions include a complete derivation.
// Editorial difficulty is provisional and should be calibrated from outcome/void logs.
const source = (title, url) => ({ title, url });
const S = {
  octopus: source('Smithsonian Ocean', 'https://ocean.si.edu/ocean-life/invertebrates/octopuses-squids-and-relatives'),
  time: source('NIST: SI measurement', 'https://nvlpubs.nist.gov/nistpubs/Legacy/LC/nbslettercircular1078.pdf'),
  metric: source('NIST: metric prefixes', 'https://www.nist.gov/pml/owm/metric-si-prefixes'),
  sun: source('NASA: Sun facts', 'https://science.nasa.gov/sun/facts/'),
  mars: source('NASA: Mars facts', 'https://science.nasa.gov/mars/facts/'),
  mercury: source('NASA: Mercury facts', 'https://science.nasa.gov/mercury/facts/'),
  wall: source('UNESCO: The Great Wall', 'https://whc.unesco.org/en/list/438/'),
  water: source('USGS: Water density', 'https://www.usgs.gov/water-science-school/science/water-density'),
  machu: source('UNESCO: Machu Picchu', 'https://whc.unesco.org/en/list/274/'),
  ocean: source('NOAA: Ocean sizes', 'https://oceanservice.noaa.gov/facts/biggestocean.html'),
  moon: source('NASA: Moon facts', 'https://science.nasa.gov/moon/facts/'),
  jupiter: source('NASA: Jupiter facts', 'https://science.nasa.gov/jupiter/jupiter-facts/'),
  suez: source('Suez Canal Authority', 'https://www.suezcanal.gov.eg/English/About/SuezCanal/Pages/AboutSuezCanal.aspx'),
  taj: source('UNESCO: Taj Mahal', 'https://whc.unesco.org/en/list/252/'),
  venus: source('NASA: Venus facts', 'https://science.nasa.gov/venus/venus-facts/'),
  antarctica: source('British Antarctic Survey', 'https://www.bas.ac.uk/about/where-we-work/antarctica/'),
  eiffel: source('Eiffel Tower: 1889 opening', 'https://www.toureiffel.paris/en/news/130-years/1889-2019-130-years-amazement'),
  flight: source('Smithsonian: 1903 Wright Flyer', 'https://airandspace.si.edu/collection-objects/1903-wright-flyer/nasm_A19610048000'),
  carbon: source('Royal Society of Chemistry: Carbon', 'https://periodic-table.rsc.org/element/6/carbon'),
  earth: source('NASA: Earth facts', 'https://science.nasa.gov/earth/facts/'),
  petra: source('UNESCO: Petra', 'https://whc.unesco.org/en/list/326/'),
  gallium: source('Royal Society of Chemistry: Gallium', 'https://periodic-table.rsc.org/element/31/gallium'),
  angkor: source('UNESCO: Angkor', 'https://whc.unesco.org/en/list/668/'),
  sydney: source('UNESCO: Sydney Opera House', 'https://whc.unesco.org/en/list/166/'),
  seasons: source('NASA: What causes the seasons?', 'https://spaceplace.nasa.gov/seasons/en/'),
  neptune: source('NASA: Discovering Neptune', 'https://www.nasa.gov/image-article/discovering-neptune/'),
  pressure: source('NOAA: Pressure and depth', 'https://oceanservice.noaa.gov/facts/pressure.html'),
  planets: source('NASA: Planetary fact sheet', 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/')
};
const rows = [
  [1, 'general-knowledge', 'How many hearts does an octopus have?', ['One', 'Two', 'Three', 'Four'], 2,
    'An octopus has three hearts: two move blood through the gills and one pumps it around the body.', ['octopus'], 'Smithsonian describes cephalopods as having three hearts: two branchial hearts and one systemic heart.', 2],
  [1, 'reasoning', 'A train leaves at 2:45 and the journey takes 90 minutes. When does it arrive?', ['3:45', '4:00', '4:15', '4:30'], 2,
    'Ninety minutes is one hour and 30 minutes. From 2:45, that gives 4:15.', [], 'Direct proof: 2:45 + 60 minutes = 3:45, then +30 minutes = 4:15.', 2],
  [1, 'comparison', 'Which planet is closest to Earth in size?', ['Mars', 'Venus', 'Mercury', 'Neptune'], 1,
    'Venus is only slightly smaller than Earth, which is why the two planets are sometimes called twins.', ['venus', 'planets'], 'NASA gives Venus a mean radius about 95% of Earth’s, much closer in size than Mars, Mercury or Neptune.', 2],
  [1, 'comparison', 'Which amount is the greatest?', ['950 millilitres', '1 litre', '1.05 litres', '900 millilitres'], 2,
    '1.05 litres is 1,050 millilitres, so it is larger than 1 litre, 950 millilitres and 900 millilitres.', ['metric'], 'Milli means one-thousandth: convert the four choices to 950, 1000, 1050 and 900 millilitres.', 2],

  [2, 'general-knowledge', 'Which planet has the shortest year?', ['Mercury', 'Venus', 'Earth', 'Mars'], 0,
    'Mercury completes one orbit of the Sun in about 88 Earth days, faster than any other planet.', ['mercury', 'planets'], 'NASA gives Mercury an orbital period of about 88 Earth days, shorter than Venus, Earth and Mars.', 2],
  [2, 'reasoning', 'Why does ordinary ice float in liquid water?', ['Ice is less dense than liquid water', 'Surface tension holds the whole cube up', 'Ice always contains enough trapped air', 'Freezing removes some of the water’s mass'], 0,
    'Ice is less dense than liquid water, so the same mass takes up more space and floats.', ['water'], 'USGS explains that ordinary ice floats because its density is lower than liquid water; freezing changes structure rather than removing mass.', 2],
  [2, 'reasoning', 'A jacket costs €60 and is reduced by 25%. What is the sale price?', ['€35', '€40', '€45', '€50'], 2,
    'Twenty-five percent of €60 is €15, so the reduced price is €45.', [], 'Direct proof: 0.25 × 60 = 15, and 60 − 15 = 45.', 2],
  [2, 'general-knowledge', 'The Great Wall was developed mainly to defend Chinese states and empires against invasions from which direction?', ['North', 'South', 'East', 'West'], 0,
    'The wall formed a defence system along China’s northern frontier against invasions from the north.', ['wall'], 'UNESCO describes the joined fortifications as a defence system against invasions from the north and places the Wall along the northern border.', 2],

  [3, 'general-knowledge', 'Which country is home to Machu Picchu?', ['Peru', 'Mexico', 'Spain', 'Brazil'], 0,
    'Machu Picchu is an Inca site high in the Peruvian Andes.', ['machu'], 'UNESCO locates the sanctuary in Peru and describes its Inca heritage.'],
  [3, 'comparison', 'Which ocean covers the largest area?', ['Atlantic', 'Indian', 'Pacific', 'Arctic'], 2,
    'The Pacific is the largest ocean basin, ahead of the Atlantic and Indian oceans.', ['ocean'], 'NOAA ranks Pacific first, Atlantic second and Indian third, with Arctic smallest.'],
  [3, 'reasoning', 'An astronaut stands on the Moon. Compared with Earth, how strongly does gravity pull them down?', ['More strongly', 'Less strongly', 'Exactly as strongly', 'There is no gravity'], 1,
    'Gravity at the Moon’s surface is about one-sixth as strong as at Earth’s surface.', ['moon'], 'NASA gives lunar surface gravity as one-sixth of Earth’s, ruling out equal, greater and zero.'],
  [3, 'comparison', 'Which has more mass: 1 kilogram of iron or 1 kilogram of feathers?', ['The iron', 'The feathers', 'They have equal mass', 'It depends on their shape'], 2,
    'Both have a mass of one kilogram. They take up very different amounts of space.', [], 'The prompt fixes both masses at exactly 1 kg; changing material or shape cannot change that equality.'],

  [4, 'comparison', 'Which is the largest planet in our solar system?', ['Earth', 'Saturn', 'Jupiter', 'Neptune'], 2,
    'Jupiter is the largest planet. Saturn is the second largest.', ['jupiter', 'planets'], 'NASA’s diameters rank Jupiter above Saturn, Neptune and Earth.'],
  [4, 'general-knowledge', 'The Suez Canal links the Mediterranean Sea to which sea?', ['Black Sea', 'Red Sea', 'Caspian Sea', 'Baltic Sea'], 1,
    'The canal crosses Egypt between the Mediterranean and the Red Sea.', ['suez'], 'The canal’s own authority identifies its two endpoints as the Mediterranean and Red Sea.'],
  [4, 'comparison', 'Which share of a pizza is the largest?', ['One half', 'Two thirds', 'Three quarters', 'One third'], 2,
    'Three quarters is 75%, larger than about 67%, 50% or 33%.', [], 'Convert to twelfths: 6/12, 8/12, 9/12 and 4/12. Nine twelfths is largest.'],
  [4, 'general-knowledge', 'Why was the Taj Mahal originally built?', ['To defend a city', 'To remember an emperor’s wife', 'To store grain', 'To study the stars'], 1,
    'Shah Jahan commissioned it in memory of his wife Mumtaz Mahal.', ['taj'], 'UNESCO describes it as a mausoleum commissioned in memory of the emperor’s wife, not a fort, granary or observatory.'],

  [5, 'comparison', 'Which planet has the hottest surface on average?', ['Mercury', 'Venus', 'Earth', 'Mars'], 1,
    'Venus’s thick atmosphere traps heat. Being closest to the Sun does not make Mercury the hottest.', ['venus'], 'NASA identifies Venus as the hottest planet and describes its runaway greenhouse effect.'],
  [5, 'comparison', 'Which continent is the driest overall, despite its huge store of ice?', ['Africa', 'Australia', 'Antarctica', 'Asia'], 2,
    'Antarctica receives very little precipitation. Much of its interior is a polar desert.', ['antarctica'], 'British Antarctic Survey explains the very low interior snowfall and desert classification; its Antarctic Lakes publication identifies Antarctica as the driest continent.'],
  [5, 'reasoning', 'A price falls by 25%, then rises by 25%. Compared with the original price, it is now…', ['Lower', 'The same', 'Higher', 'Exactly double'], 0,
    'The increase applies to a smaller amount. Starting at 100 gives 75, then 93.75.', [], 'For original price P > 0, 0.75P × 1.25 = 0.9375P < P; no currency or rounding assumptions needed.'],
  [5, 'chronology', 'Which event happened in the 1800s?', ['The Eiffel Tower opened', 'The Wright brothers’ first powered flights', 'Sydney Opera House opened', 'The Taj Mahal was built'], 0,
    'The Eiffel Tower opened in 1889. The others date to 1903, 1973 and the 1600s.', ['eiffel', 'flight', 'sydney', 'taj'], 'Official sources date Eiffel to 1889, Wright flights to 1903, Sydney to 1973 and Taj to the seventeenth century. Only 1889 lies in 1800–1899.'],

  [6, 'general-knowledge', 'Diamond and graphite are different forms of which element?', ['Carbon', 'Iron', 'Silicon', 'Calcium'], 0,
    'Both are carbon. Their atoms are arranged differently, giving them very different properties.', ['carbon'], 'RSC identifies diamond and graphite as forms of carbon, excluding the three other chemical elements.'],
  [6, 'estimation', 'Which gas makes up most of the dry air near Earth’s surface?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], 1,
    'Dry air is about 78% nitrogen and 21% oxygen.', ['earth'], 'NASA lists nitrogen at 78%, oxygen 21%, with other gases making up about 1%.'],
  [6, 'inference', 'Petra stood in a dry landscape. What helped its ancient population obtain enough water?', ['Collecting seasonal rain', 'Melting nearby glaciers', 'Drawing from a large natural lake', 'Diverting a year-round river'], 0,
    'Petra used channels, dams and reservoirs to collect and conserve seasonal rain.', ['petra'], 'UNESCO explicitly credits water management and the storage of seasonal rains with supporting settlement in an arid area. Other choices do not describe this system.'],
  [6, 'reasoning', 'A cube’s height, width and depth are all doubled. Its volume becomes…', ['Twice as large', 'Four times as large', 'Six times as large', 'Eight times as large'], 3,
    'Doubling each of three dimensions gives 2 × 2 × 2 = 8 times the volume.', [], 'For side s, (2s)^3 / s^3 = 8. Linear, square and additive distractors give distinct incorrect ratios.'],

  [7, 'comparison', 'Which planet takes longer to spin once than to orbit the Sun once?', ['Earth', 'Mars', 'Venus', 'Jupiter'], 2,
    'Venus spins once in about 243 Earth days and orbits the Sun in about 225.', ['venus', 'planets'], 'Compare absolute sidereal rotation with orbital periods; only Venus among these four has rotation longer than its year. This is not a sunrise-to-sunrise day.'],
  [7, 'general-knowledge', 'Which metal melts at about 30°C, close to the temperature of a warm room?', ['Iron', 'Copper', 'Gallium', 'Aluminium'], 2,
    'Gallium melts at about 29.8°C, far below the melting points of these other metals.', ['gallium'], 'RSC fact box gives 29.7646°C. Iron, copper and aluminium melt well above ordinary room temperature.'],
  [7, 'reasoning', 'Two fair six-sided dice are rolled. Which total is most likely?', ['Five', 'Six', 'Seven', 'Eight'], 2,
    'Seven has six possible ordered pairs. Five has four; six and eight each have five.', [], 'Enumerate the 36 equally likely ordered pairs: sums 5,6,7,8 occur 4,5,6,5 times.'],
  [7, 'general-knowledge', 'The temple complex of Angkor is in which country?', ['Thailand', 'Cambodia', 'Vietnam', 'Laos'], 1,
    'Angkor is in Cambodia and preserves major works of the Khmer Empire.', ['angkor'], 'UNESCO assigns Angkor to Cambodia and describes it as a centre of the Khmer Empire.'],

  [8, 'estimation', 'About how long does sunlight take to reach Earth?', ['8 seconds', '8 minutes', '8 hours', '8 days'], 1,
    'Sunlight takes roughly eight minutes to cross the space from the Sun to Earth.', ['venus'], 'NASA’s Venus size-and-distance section explicitly compares six minutes to Venus with about eight to Earth.'],
  [8, 'chronology', 'Which of these landmarks was completed most recently?', ['Taj Mahal', 'Eiffel Tower', 'Sydney Opera House', 'Great Wall’s Ming-era sections'], 2,
    'Sydney Opera House opened in 1973, long after the other three were built.', ['sydney', 'taj', 'eiffel', 'wall'], 'UNESCO: Sydney inaugurated 1973; Taj main tomb 1648, complex 1653; Great Wall Ming construction before 1644. Eiffel official opening 1889.'],
  [8, 'inference', 'Why do the Northern and Southern Hemispheres have opposite seasons?', ['Earth’s axis is tilted', 'The Sun changes size', 'The Moon blocks sunlight', 'Earth reverses its spin'], 0,
    'Earth’s tilt makes one hemisphere lean toward the Sun while the other leans away.', ['seasons'], 'NASA explains opposite hemispheric seasons by the tilted rotation axis and its orientation during Earth’s orbit.'],
  [8, 'reasoning', 'After a 20% price cut, what percentage increase restores the original price?', ['20%', '25%', '30%', '40%'], 1,
    'A price of 100 falls to 80. Adding 20 to 80 is a 25% increase.', [], 'Required factor is 1/0.8 = 1.25, hence 25%. Multiplying 0.8 by the other factors does not return 1.'],

  [9, 'general-knowledge', 'Which planet was located after calculations predicted where to look for it?', ['Mars', 'Saturn', 'Uranus', 'Neptune'], 3,
    'Neptune’s position was predicted from its gravitational effect on Uranus’s orbit.', ['neptune'], 'NASA identifies Neptune as the first planet located through mathematical predictions. Uranus was discovered by telescope, while Mars and Saturn were known in antiquity.'],
  [9, 'estimation', 'At about 30 metres below the sea surface, total pressure is roughly how many times sea-level air pressure?', ['Two', 'Three', 'Four', 'Ten'], 2,
    'The water adds about one atmosphere per 10 metres, on top of the atmosphere already above it.', ['pressure'], 'NOAA: add roughly 1 atmosphere per 10.06 m. At 30 m, 1 + 30/10.06 ≈ 4 atmospheres total.'],
  [9, 'comparison', 'Which of Earth’s five oceans is third-largest by area?', ['Arctic', 'Southern', 'Indian', 'Atlantic'], 2,
    'The order is Pacific, Atlantic, Indian, Southern, then Arctic.', ['ocean'], 'NOAA provides this explicit ordering of ocean basins by area.'],
  [9, 'reasoning', 'Three fair coins are tossed independently. What is the chance of exactly two heads?', ['1 in 8', '1 in 4', '3 in 8', '1 in 2'], 2,
    'HHT, HTH and THH are three of the eight equally likely outcomes.', [], 'Enumerated outcomes HHH,HHT,HTH,HTT,THH,THT,TTH,TTT; exactly two heads appears in 3/8.'],

  [10, 'comparison', 'At normal air pressure, pure liquid water is densest at approximately which temperature?', ['0°C', '4°C', '20°C', '100°C'], 1,
    'Water reaches its maximum density around 4°C. Cooling it further makes it expand.', ['water'], 'USGS identifies maximum water density at 4°C; this differs from water’s freezing point.'],
  [10, 'comparison', 'Which planet completes one spin in the shortest time?', ['Earth', 'Jupiter', 'Saturn', 'Neptune'], 1,
    'Jupiter spins in about 9.9 hours, slightly faster than Saturn.', ['jupiter', 'planets'], 'NASA explicitly identifies Jupiter’s day as shortest; fact sheet lists 9.9h against Saturn 10.7h, Neptune 16.1h and Earth about 24h.'],
  [10, 'reasoning', 'A circular rope grows 1 metre longer and is raised evenly all around. About how much does its radius increase?', ['1 millimetre', '1 centimetre', '16 centimetres', '1 metre'], 2,
    'Circumference is 2πr. An extra metre adds 1 ÷ 2π metres to the radius: about 16 cm, whatever the original size.', [], 'Subtract C1=2πr1 from C2=2πr2. Δr=1/(2π)m≈0.15915m=15.915cm. Only 16cm is a reasonable approximation.'],
  [10, 'comparison', 'Which planet has the greatest average density?', ['Mercury', 'Venus', 'Earth', 'Jupiter'], 2,
    'Earth is slightly denser on average than Mercury, despite Jupiter being far more massive.', ['planets'], 'NASA fact sheet in kg/m³: Earth 5514, Mercury 5429, Venus 5243, Jupiter 1326. Compare density, not total mass.']
];

export const QUESTIONS = rows.map(([rung, family, prompt, options, answer, explanation, keys, evidence, revision = 1], index) => Object.freeze({
  id: `millionaire-${String(index + 1).padStart(3, '0')}${revision > 1 ? `-v${revision}` : ''}`, rung, family, prompt, options, answer, explanation,
  difficulty: { rung, band: rung <= 3 ? 'opening' : rung <= 6 ? 'middle' : rung <= 9 ? 'pressure' : 'final', calibration: 'editorial' },
  sources: keys.map(key => S[key]), evidence,
  reviewedAt: revision > 1 ? '2026-10-04' : '2026-10-02', review: 'Key, distractors, plain English, cultural accessibility and single-answer check completed.'
}));