// Server-only content. Never serve this file or send the deck to either browser.
const lines = `
umbrella|rain,wet,weather,cover
airport|plane,fly,travel,flight
library|book,read,quiet,borrow
birthday|cake,party,age,present
dentist|teeth,mouth,doctor,pain
mountain|high,climb,hill,snow
refrigerator|cold,food,kitchen,fridge
passport|travel,country,document,identity
elephant|trunk,big,animal,grey
restaurant|food,eat,menu,waiter
mirror|reflection,look,glass,face
bridge|river,cross,road,water
neighbor|live,house,next,near
breakfast|morning,eat,meal,eggs
beach|sand,sea,ocean,sun
wallet|money,cash,cards,pocket
traffic|cars,road,jam,drive
secret|tell,know,hidden,private
garden|plants,flowers,grow,outside
photograph|picture,camera,take,image
adventure|travel,exciting,explore,journey
honest|truth,lie,trust,sincere
jealous|envy,want,other,relationship
comfortable|relax,soft,chair,cozy
generous|give,kind,money,share
elegant|classy,stylish,sophisticated,graceful
stubborn|change,mind,refuse,stuck
patient|wait,calm,time,hospital
delicious|taste,food,eat,good
exhausted|tired,sleep,energy,rest
proud|achievement,happy,success,pleased
curious|questions,know,interested,learn
lonely|alone,friends,sad,people
brave|fear,scared,courage,danger
polite|please,thank,rude,manners
surprise|expect,unexpected,gift,shock
promise|keep,word,swear,commitment
mistake|wrong,error,accident,correct
memory|remember,past,forget,brain
dream|sleep,night,imagine,wish
freedom|free,choice,prison,rules
deadline|time,finish,date,work
habit|always,routine,repeat,do
opinion|think,believe,view,agree
advice|should,suggest,help,recommend
complaint|problem,unhappy,service,bad
invitation|party,come,invite,event
decision|choose,choice,option,decide
excuse|reason,sorry,late,explain
opportunity|chance,possible,offer,job
competition|win,lose,game,prize
teamwork|together,group,cooperate,team
recycle|reuse,plastic,waste,bin
volunteer|help,free,work,charity
apologize|sorry,mistake,forgive,regret
celebrate|party,happy,occasion,enjoy
whisper|quiet,voice,speak,secret
argue|fight,disagree,angry,shout
borrow|lend,return,take,money
repair|fix,broken,work,damage
discover|find,new,explore,unknown
pretend|act,fake,real,imagine
recommend|suggest,advice,good,try
improve|better,progress,practice,change
escape|leave,run,prison,free
balance|fall,steady,equal,weight
recipe|cook,food,ingredients,instructions
suitcase|travel,bag,clothes,pack
elevator|lift,up,down,floor
keyboard|type,computer,letters,keys
headphones|music,ears,listen,sound
candle|light,flame,wax,burn
ladder|climb,steps,up,high
scissors|cut,paper,sharp,blades
pillow|sleep,bed,head,soft
blanket|warm,bed,cover,cold
soap|wash,clean,hands,bubbles
toothbrush|teeth,clean,mouth,paste
envelope|letter,mail,paper,stamp
newspaper|news,read,paper,articles
dictionary|word,meaning,definition,language
calendar|date,month,year,day
receipt|buy,pay,shop,paper
discount|price,cheap,sale,money
salary|money,job,pay,work
interview|job,questions,answers,meeting
appointment|time,meet,doctor,schedule
commute|work,travel,home,train
retirement|work,old,job,pension
vacation|holiday,travel,rest,trip
souvenir|travel,gift,remember,trip
museum|art,history,exhibition,visit
theater|stage,actors,play,show
concert|music,band,singer,live
audience|watch,people,show,clap
stadium|sport,football,crowd,match
referee|rules,game,whistle,judge
medal|win,gold,prize,sport
rainbow|colors,rain,sky,sun
thunder|storm,noise,lightning,loud
shadow|dark,light,sun,shape
island|water,sea,land,ocean
desert|sand,hot,dry,water
forest|trees,woods,nature,green
waterfall|water,river,fall,cliff
earthquake|ground,shake,disaster,buildings
butterfly|wings,insect,fly,colors
penguin|bird,ice,black,white
dolphin|sea,swim,animal,fish
octopus|eight,arms,sea,tentacles
honey|bee,sweet,sugar,yellow
onion|cry,vegetable,layers,cook
popcorn|movie,corn,snack,cinema
sandwich|bread,fill,eat,lunch
chocolate|sweet,cocoa,brown,candy
lemon|yellow,sour,fruit,juice
garlic|smell,cook,white,flavor
ice cream|cold,sweet,frozen,dessert
bicycle|bike,wheels,ride,pedal
helmet|head,protect,safety,wear
seat belt|car,safety,fasten,strap
firefighter|fire,water,save,truck
plumber|pipes,water,repair,leak
architect|building,design,house,plans
scientist|experiment,research,lab,science
lawyer|law,court,judge,legal
farmer|farm,grow,animals,fields
cashier|pay,shop,money,till
waiter|restaurant,food,serve,table
tourist|travel,visit,holiday,foreign
friendship|friend,together,trust,relationship
respect|admire,polite,treat,value
patience|wait,calm,time,patient
confidence|believe,sure,self,trust
creativity|ideas,imagine,original,create
responsibility|duty,job,care,accountable
tradition|custom,culture,family,old
pollution|dirty,air,environment,waste
reputation|people,opinion,known,image
permission|allow,can,ask,yes
progress|improve,forward,better,development
`
  .trim()
  .split("\n");
export const CARDS = lines.map((line) => {
  const [target, words] = line.split("|");
  return { target, forbidden: words.split(",") };
});
